kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c53ec07d9453d088 # go to efs console and copy the file system id it wii change every time when ur doing project
  directoryPerms: "700"
  basePath: "/expense"
