apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04fd7019fbab2765c # go to efs console and copy the file system id