apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer # This is the key difference, it exposes the service on a port on each node
  selector:
   purpose: efs-static-demo # labels are set as selectors here
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose
    targetPort: 80
    nodePort: 30007 # The port on the container that the service will forward to
---