apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://dockerhub.com/"
 
spec:
  containers:
  - name: nginx
    image: nginx
 