apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # deployment labels
  labels:
    app: nginx
    tier: frontend
    pupose: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      pupose: Deployment  
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        pupose: Deployment
    spec:
      containers:
      - name: nginx
        image: peddireddylokesh/deployment:2.0
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer # This is the key difference, it exposes the service on a port on each node
  selector:
    app: nginx
    tier: frontend
    pupose: Deployment  
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose
    targetPort: 80
    nodePort: 30007 # The port on the container that the service will forward to
---