apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["/bin/bash", "-c","sleep":"1000"]
