apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
# one pod can mutiple containers
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

