apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: backend
    environment: dev # labels are set as selectors here 
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose
    targetPort: 80 # The port on the container that the service will forward to
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
      project: expense
      component: backend
      environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
   